version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: load_booking_postgres
    environment:
      POSTGRES_DB: load_booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - load_booking_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: load_booking_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cargopro.ai
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - load_booking_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  load_booking_network:
    driver: bridge