server:
  port: 8080
  
spring:
  application:
    name: load-booking-system
  
  datasource:
    url: jdbc:postgresql://localhost:5432/load_booking_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
logging:
  level:
    com.cargopro.loadbooking: DEBUG
    org.springframework.web: DEBUG